apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flaskapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployement
    name: flaskapi
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50