apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: katja16j/flask-api:ba81a65e53c715bd77d20157b93d23b9fab55146
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service 
metadata:
  name: flaskapi
spec:
  type: LoadBalancer
  selector:
    app: flaskapi
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000